security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:

            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout: true
            anonymous: true

    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: ROLE_ADMIN }
      - { path: ^/admin, role: ROLE_ADMIN }
      - { path: ^/_profiler_home, role: ROLE_USER }

      - { path: ^/_profiler_phpinfo, role: ROLE_ADMIN }
      - { path: ^/_profiler_search_results, role: ROLE_USER }
      - { path: ^/_profiler_open_file, role: ROLE_USER }
      - { path: ^/_profiler, role: ROLE_USER }
      - { path: ^/_profiler_router, role: ROLE_USER }
      - { path: ^/_profiler_exception, role: ROLE_ADMIN }
      - { path: ^/_profiler_exception_css, role: ROLE_ADMIN }
      - { path: ^/_twig_error_test, role: ROLE_ADMIN }
      - { path: ^/register, role: ROLE_ADMIN }
      - { path: ^/, role: ROLE_USER }
      - { path: ^/add_chambre, role: ROLE_USER }
      - { path: ^/add_file, role: ROLE_USER }
      - { path: ^/add_ref, role: ROLE_USER }
      - { path: ^/creer, role: ROLE_USER }
      - { path: ^/chambre, role: ROLE_USER }
      - { path: ^/ref, role: ROLE_USER }
      - { path: ^/fichier, role: ROLE_USER }
      - { path: ^/delete_dossier, role: ROLE_USER }
      - { path: ^/deleteRef, role: ROLE_USER }
      - { path: ^/delete_chambre, role: ROLE_USER }
      - { path: ^/delete_PieceJointe, role: ROLE_USER }
      - { path: ^/editRef, role: ROLE_USER }
      - { path: ^/editChambre, role: ROLE_USER }
      - { path: ^/editPiece, role: ROLE_USER }
      - { path: ^/list_dossier, role: ROLE_USER }
      - { path: ^/open_dossier, role: ROLE_USER }
      - { path: ^/search, role: ROLE_USER }
      - { path: ^/searchNom, role: ROLE_USER }
      - { path: ^/fos_user_security_login, role: ROLE_ADMIN}
      - { path: ^/fos_user_security_check, role: ROLE_ADMIN}
      - { path: ^/fos_user_security_logout, role: ROLE_ADMIN}
      - { path: ^/fos_user_profile_show, role: ROLE_USER}
      - { path: ^/fos_user_profile_edit, role: ROLE_USER}
      - { path: ^/fos_user_registration_register, role: ROLE_ADMIN}
      - { path: ^/fos_user_registration_check_email, role: ROLE_ADMIN}
      - { path: ^/fos_user_registration_confirm, role: ROLE_ADMIN}
      - { path: ^/fos_user_registration_confirmed, role: ROLE_ADMIN}
      - { path: ^/fos_user_resetting_request, role: ROLE_ADMIN}
